apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../bases/home-assistant

labels:
  - includeSelectors: false
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: home-assistant
      app.kubernetes.io/managed-by: argocd
      app.kubernetes.io/component: home-automation
      app.kubernetes.io/version: "2023.12"
