apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: base
  repo: https://istio-release.storage.googleapis.com/charts
  releaseName: istio-base
  namespace: istio
  version: 1.19.0
  includeCRDs: true

