apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../bases/cert-manager

labels:
  - includeSelectors: false
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: cloudflared
      app.kubernetes.io/managed-by: argocd
      app.kubernetes.io/component: certificate
      app.kubernetes.io/version: 1.13.1


