apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  annotations:
    # prevent dry run failure when CRD not installed yet
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@nandi.sh
    privateKeySecretRef:
      name: letsencrypt
    # use DNS01 for challenges
    # https://cert-manager.io/docs/configuration/acme/dns01/
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
