apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: homelab-lb
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  addresses:
    # The IP addresses for the lb
    - 10.43.10.100-10.43.10.120
