apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: home-assistant
  name: home-assistant
  labels:
    app: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: home-assistant
    spec:

      containers:
        - name: home-assistant
          image: homeassistant/home-assistant:2023.12
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
          ports:
            - containerPort: 8123
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /config/configuration.yaml
              subPath: configuration.yaml
              name: configmap-file
            - mountPath: /config/automations.yaml
              subPath: automations.yaml
              name: configmap-file
            - mountPath: /run/dbus
              name: d-bus
              readOnly: true
          #- mountPath: /dev/video0
          #  name: cam
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
                - SYS_ADMIN
      hostNetwork: true
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: home-assistant-pvc
        - name: configmap-file
          configMap:
            name: home-assistant-configmap
        #  hostPath:
        #    path: /tmp/home-assistant
        #    type: DirectoryOrCreate
        - name: d-bus
          hostPath:
            path: /run/dbus
