---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
spec:
  ports:
    - port: 8123
      protocol: TCP
  selector:
    app: home-assistant
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: home-assistant-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http2
        protocol: HTTP
      hosts:
        - "homelab.nandi.sh"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: home-assistant
spec:
  hosts:
    - "homelab.nandi.sh"
  gateways:
    - home-assistant-gateway
  http:
    - name: "homelab"
      route:
        - destination:
            host: home-assistant
            port:
              number: 8123
