apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-system

resources:
  - ../../../bases/istio-base
  - ../../../bases/istio-gateway
  - ../../../bases/istiod

labels:
  - includeSelectors: false
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: istio
      app.kubernetes.io/managed-by: argocd
      app.kubernetes.io/component: network
      app.kubernetes.io/version: 1.19.0
