apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../bases/cloudflared

labels:
  - includeSelectors: false
    includeTemplates: true
    pairs:
      app.kubernetes.io/name: cloudflared
      app.kubernetes.io/managed-by: argocd
      app.kubernetes.io/component: network
      app.kubernetes.io/version: 2023.8.2-arm64

images:
  - name: cloudflare/cloudflared
    newTag: 2023.8.2-arm64

