apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-dashboard-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
  data:
    - secretKey: grafana-dashboard
      remoteRef:
        key: username
        property: username
    - secretKey: grafana-dashboard
      remoteRef:
        key: password
        property: password
