apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-dashboard-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    name: grafana-dashboard-credentials
  dataFrom:
    - extract:
        key: grafana-dashboard
