apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: grafana
    repo: https://grafana.github.io/helm-charts
    releaseName: grafana
    namespace: grafana
    additionalValuesFiles:
      - values-upstream.yaml
      - values.yaml
    version: 7.0.19

resources:
  - external-secret.yaml
  - service.yaml

