apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana
spec:
  hosts:
    - "homelab.nandi.sh"
  gateways:
    # TODO: move to a shared gateway
    - home-assistant/home-assistant-gateway
  http:
    - name: "homelab-grafana"
      match:
        - uri:
            prefix: "/grafana"
      rewrite:
        uri: ""
      route:
        - destination:
            host: grafana
            port:
              number: 80
