apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: grafana-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http2
        protocol: HTTP
      hosts:
        - "homelab.nandi.sh"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana
spec:
  hosts:
    - "homelab.nandi.sh"
  gateways:
    - home-assistant-gateway
  http:
    - name: "homelab"
      match:
        - uri:
            prefix: "/grafana"
      rewrite:
        uri: "/"
      route:
        - destination:
            host: grafana
            port:
              number: 80
