apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: prometheus
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: prometheus
    namespace: prometheus
    additionalValuesFiles:
      - values-upstream.yaml
      - values.yaml
    version: 25.8.2

resources: []

