apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apps/cloudflared.yaml
  - apps/metallb.yaml
  - apps/prometheus.yaml
  - apps/longhorn.yaml
  - apps/grafana.yaml
  - apps/istio.yaml
  - apps/cert-manager.yaml
  - apps/home-assistant.yaml
patches:
  - path: argocd-app-patch.yaml
    target:
      kind: Application
