apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - apps/istio.yaml
  - apps/cloudflared.yaml
  - apps/cert-manager.yaml
  - apps/metallb.yaml

patches:
  - path: argocd-app-patch.yaml
    target:
      kind: Application
