apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - telemetry.yaml

helmCharts:
- name: istiod
  repo: https://istio-release.storage.googleapis.com/charts
  releaseName: istiod
  namespace: istio-system
  version: 1.19.0
  valuesFile: values.yaml
