apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


helmCharts:
- name: istiod
  repo: https://istio-release.storage.googleapis.com/charts
  releaseName: istiod
  namespace: istio
  version: 1.19.0
